<?php

return [
    'min_image_side' => 300,
    'min_image_pixels' => 40000,
    'generic_duplicate_min_products' => 8,
    'generic_duplicate_min_brands' => 2,
    'remote_timeout' => 8,
    'chunk_size' => 100,
    'huawei_sku' => '02356UUM',
    'reports_dir' => 'reports',
    'manufacturer_brands' => [
        'Ubiquiti',
        'UniFi',
        'MikroTik',
        'Dahua',
        'Hikvision',
        'Dell',
        'HP',
        'Hewlett Packard',
        'Hewlett-Packard',
        'Lenovo',
        'ASUS',
        'Asus',
        'TP-Link',
        'TP Link',
        'Tplink',
        'Synology',
        'APC',
        'Schneider Electric',
        'Yealink',
        'Huawei',
        'Teltonika',
    ],
];
