<?php

return [
    /*
    | Esquire / distributor CategoryHead values treated as IT departments.
    | Categories under these heads are kept unless they match excluded_category_terms.
    | Top-level categories NOT in this list (orphan categories) are non-IT by default.
    */
    'it_category_heads' => [
        'Batteries',
        'Bluetooth Products',
        'CCTV and DVR Accessories',
        'CCTV and DVR Products',
        'Cables & Adapters',
        'Cameras & Camcorders',
        'Car Electronics',
        'Computer Chassis',
        'Computer Cooling',
        'Computer Gaming Accessories',
        'Computer Gaming Hardware',
        'Computer Graphic Cards',
        'Computer I/O Controllers',
        'Computer Memory',
        'Computer Monitor Accessories',
        'Computer Monitors',
        'Computer Motherboards',
        'Computer Optical Drives',
        'Computer Processors',
        'Computer Software',
        'Console Gaming Accessories',
        'Console Gaming Units',
        'Desktop  Computers',
        'Flash Memory products',
        'Gadgets and Gifts',
        'HDMI Products',
        'Hard Drive Enclosures',
        'Hard Drives/Storage',
        'IP Camera Products',
        'KVM Switches',
        'Keyboards and Mice',
        'LED Lightning',
        'Licensed Products',
        'Line Drivers & Extenders',
        'Media Storage Solutions',
        'Mobile Phone Accessories',
        'Mobile Phone Covers',
        'Mobile and Smartphones',
        'Modems & Routers',
        'Multimedia Accessories',
        'Multimedia Players',
        'Networking-Active',
        'Networking-Passive',
        'Notebook Accessories',
        'Notebook Bags and Cases',
        'Notebooks and Laptops',
        'Office Products',
        'Otg Products',
        'Peripherals',
        'Point of Sale Products',
        'Power Supplies',
        'Printer Accessories',
        'Printers',
        'Projectors and Accessories',
        'Renewable Power Solutions',
        'Server Products',
        'Smart Boards',
        'Smart Home',
        'Speakers & Audio',
        "Tablet PC's",
        "Tablet PC's Accessories",
        "Tablet PC's Covers",
        'Telephone Equipment',
        'Televisions',
        'Televisions- Accessories',
        'Toolkit and Test equipment',
        'USB Peripherals',
        'Uninterruptible Power Supply',
        'WebCams',
        'Wireless Network Products',
    ],

    /*
    | Orphan categories (no IT CategoryHead) that should still be kept.
    */
    'it_category_exceptions' => [
        'Samsung Tablet Covers',
        'Cable Clips',
        'Disks: CD&DVD/R/RW/Floppy',
        'Document Scanners',
    ],

    /*
    | Non-IT category/product terms — matched case-insensitively against
    | category names (and import category paths). Products in matching
    | categories are removed and future CSV rows are skipped.
    */
    'excluded_category_terms' => [
        'lady shaver',
        'men shaver',
        'electric shaver',
        'shaver',
        'hair straightener',
        'hair clipper',
        'hair trimmer',
        'hair dryer',
        'garment steamer',
        'dictionary',
        'dictionaries',
        'shoe rack',
        'shoe racks',
        'bathroom accessor',
        'bathroom accessories',
        'bathroom scale',
        'vacuum sealer',
        'plastic bag sealer',
        'counterbook',
        'counter book',
        'a4 counterbook',
        'book cover',
        'book covers',
        'precut book',
        'slipon book',
        'cleaning - mop',
        'mops & broom',
        'mop bucket',
        'microfibre cloth',
        'waste bin',
        'ironing board',
        'clothes horse',
        'laundry basket',
        'washing machine',
        'microwave',
        'air fryer',
        'toaster',
        'sandwich toaster',
        'pressure cooker',
        'induction cooker',
        'jug blender',
        'hand/stick blender',
        'milk frother',
        'pots & pan',
        'cutlery set',
        'knife set',
        'kitchen utensil',
        'salt & pepper',
        'water jug',
        'water dispenser',
        'air purifier',
        'airconditioning',
        'heater',
        'vacuum cleaner',
        'car accessor',
        'luggage scale',
        'home safe',
        'toy basket',
        'toys/misc',
        'fidget roller',
        'fidget gadget',
        'personal care',
        'beauty',
        'cosmetic',
        'homeware',
        'home ware',
        'kitchenware',
        'stationery',
        'ballpoint pen',
        'whiteboard marker',
        'permanent marking pen',
        'pencil case',
        'exercise book',
        'fashion',
        'apparel',
        'clothing',
        'footwear',
        'furniture',
        'tables & chair',
        'tv stand',
        'toys',
        'garden',
        'pets',
        'health & beauty',
        'home & living',
        'household',
        'nitrile glove',
        'oxygen therapy',
        'health patch',
        'disney product',
        'kids swimming',
        'sport accessor',
        'key ring',
        'keyring',
        'keyrings',
        'cleaning brush',
        'high pressure washer',
        'pressure washer',
        'cellphone case',
        'cell phone case',
        'phone case',
        'electric toothbrush',
        'toothbrush',
        'fridges',
        'fridge',
        'freezers',
        'freezer',
        'rope',
        'file divider',
        'stapler',
        'staples',
        'dustbin',
        'dust pan',
        'swimming vest',
        'water bottle',
        'lunch box',
        'umbrella',
        'torch',
        'flashlight',
    ],

    /*
    | Extra terms matched against product name and short description.
    | Category terms above are always checked on products too.
    */
    'excluded_product_terms' => [
        'lady shaver',
        'men shaver',
        'electric shaver',
        'shaver',
        'hair straightener',
        'dictionary',
        'dictionaries',
        'shoe rack',
        'bathroom scale',
        'vacuum sealer',
        'counterbook',
        'counter book',
        'a4 counterbook',
        'book cover',
        'precut book',
        'exercise book',
        'mop bucket',
        'dust pan',
        'ironing board',
        'clothes horse',
        'laundry basket',
        'food sealer',
        'freezer storage bag',
        'kitchen utensil',
        'pencil, retail',
        'tweety pencil',
    ],

    /*
    | Pinnacle distributor CSV feeds (category_tree slash paths).
    | Roots listed here are treated as IT; others are skipped on import.
    */
    'pinnacle_category_roots' => [
        'computing',
        'security',
        'networking',
        'point-of-sale',
        'enterprise',
        'infrastructure',
    ],

    'excluded_pinnacle_roots' => [
        'on-promo',
    ],
];
