<?php

/**
 * Canonical Urban Focus category tree (main categories + subcategories).
 * Used by CategoryReorganizationService, CategoryMapperService, and admin tooling.
 */
return [
    'tree' => [
        [
            'name' => 'Electronics, Security & Surveillance',
            'slug' => 'security-surveillance',
            'description' => 'CCTV, access control, alarms, vehicle dash cameras, fleet monitoring, GPS tracking and professional security electronics for homes and businesses across South Africa.',
            'meta_title' => 'Security, Surveillance & Fleet Electronics | Urban Focus',
            'meta_description' => 'Shop CCTV cameras, NVRs, dash cams, GPS trackers, fleet monitoring, access control and security electronics at Urban Focus with nationwide delivery.',
            'children' => [
                ['name' => 'CCTV Cameras', 'slug' => 'cctv-cameras'],
                ['name' => 'IP Cameras', 'slug' => 'ip-cameras'],
                ['name' => 'PTZ Cameras', 'slug' => 'ptz-cameras'],
                ['name' => 'Solar Cameras', 'slug' => 'solar-cameras'],
                ['name' => 'NVR Systems', 'slug' => 'nvr-systems'],
                ['name' => 'DVR Systems', 'slug' => 'dvr-systems'],
                ['name' => 'CCTV Accessories', 'slug' => 'cctv-accessories'],
                ['name' => 'CCTV Cables', 'slug' => 'cctv-cables'],
                ['name' => 'Access Control', 'slug' => 'access-control'],
                ['name' => 'Biometric Systems', 'slug' => 'biometric-systems'],
                ['name' => 'Alarm Systems', 'slug' => 'alarm-systems'],
                ['name' => 'Intercom Systems', 'slug' => 'intercom-systems'],
                ['name' => 'Smart Locks', 'slug' => 'smart-locks'],
                ['name' => 'AI Cameras', 'slug' => 'ai-cameras'],
                ['name' => 'Facial Recognition Systems', 'slug' => 'facial-recognition-systems'],
                ['name' => 'Dash Cameras', 'slug' => 'dash-cameras'],
                ['name' => 'AI Dash Cameras', 'slug' => 'ai-dash-cameras'],
                ['name' => 'GPS Trackers', 'slug' => 'gps-trackers'],
                ['name' => 'Reverse Cameras', 'slug' => 'reverse-cameras'],
                ['name' => 'MDVR Systems', 'slug' => 'mdvr-systems'],
                ['name' => 'Body Worn Cameras', 'slug' => 'body-worn-cameras'],
                ['name' => 'Smart Helmet Cameras', 'slug' => 'smart-helmet-cameras'],
                ['name' => 'Passenger Counting Systems', 'slug' => 'passenger-counting-systems'],
                ['name' => 'Driver Monitoring Systems', 'slug' => 'driver-monitoring-systems'],
                ['name' => 'Fleet Monitoring Systems', 'slug' => 'fleet-monitoring-systems'],
            ],
        ],
        [
            'name' => 'Networking & Connectivity',
            'slug' => 'networking-connectivity',
            'description' => 'Routers, switches, access points, fibre, PoE and wireless networking for business and home connectivity.',
            'meta_title' => 'Networking & Connectivity | Urban Focus',
            'meta_description' => 'Shop routers, switches, access points, fibre and network cabling at Urban Focus with expert IT support and nationwide delivery.',
            'children' => [
                ['name' => 'Routers', 'slug' => 'routers'],
                ['name' => 'Access Points', 'slug' => 'access-points'],
                ['name' => 'Switches', 'slug' => 'switches'],
                ['name' => 'POE Equipment', 'slug' => 'poe-equipment'],
                ['name' => 'Fibre Equipment', 'slug' => 'fibre-equipment'],
                ['name' => 'Network Cabinets', 'slug' => 'network-cabinets'],
                ['name' => 'Network Cables', 'slug' => 'network-cables'],
                ['name' => 'Wireless Bridges', 'slug' => 'wireless-bridges'],
                ['name' => 'Starlink Accessories', 'slug' => 'starlink-accessories'],
            ],
        ],
        [
            'name' => 'Solar & Power Solutions',
            'slug' => 'solar-power',
            'description' => 'Inverters, batteries, UPS, solar kits and backup power for homes, offices and security installations.',
            'meta_title' => 'Solar & Power Solutions | Urban Focus',
            'meta_description' => 'Inverters, batteries, UPS systems and solar power solutions from Urban Focus with professional advice and delivery across South Africa.',
            'children' => [
                ['name' => 'Inverters', 'slug' => 'inverters'],
                ['name' => 'Batteries', 'slug' => 'batteries'],
                ['name' => 'Solar Security Cameras', 'slug' => 'solar-security-cameras'],
                ['name' => 'Solar Floodlights', 'slug' => 'solar-floodlights'],
                ['name' => 'Portable Power Stations', 'slug' => 'portable-power-stations'],
                ['name' => 'UPS Systems', 'slug' => 'ups-systems'],
                ['name' => 'Solar Kits', 'slug' => 'solar-kits'],
                ['name' => 'Power Backup Solutions', 'slug' => 'power-backup-solutions'],
            ],
        ],
        [
            'name' => 'Digital Signage & Displays',
            'slug' => 'digital-signage',
            'description' => 'Indoor and outdoor displays, LED screens, kiosks and media players for retail, transport and corporate signage.',
            'meta_title' => 'Digital Signage & Displays | Urban Focus',
            'meta_description' => 'Digital signage, LED displays, touch kiosks and media players from Urban Focus for retail, transport and corporate environments.',
            'children' => [
                ['name' => 'Indoor Displays', 'slug' => 'indoor-displays'],
                ['name' => 'Outdoor Displays', 'slug' => 'outdoor-displays'],
                ['name' => 'Bus Advertising Screens', 'slug' => 'bus-advertising-screens'],
                ['name' => 'Taxi Screens', 'slug' => 'taxi-screens'],
                ['name' => 'LED Displays', 'slug' => 'led-displays'],
                ['name' => 'Touch Kiosks', 'slug' => 'touch-kiosks'],
                ['name' => 'Media Players', 'slug' => 'media-players'],
                ['name' => 'Interactive Displays', 'slug' => 'interactive-displays'],
            ],
        ],
        [
            'name' => 'Computing & Office Technology',
            'slug' => 'computing-office',
            'description' => 'Laptops, desktops, monitors, printers, scanners and office technology for modern workplaces.',
            'meta_title' => 'Computing & Office Technology | Urban Focus',
            'meta_description' => 'Business laptops, desktops, monitors, printers and office technology from Urban Focus with VAT invoices and nationwide delivery.',
            'children' => [
                ['name' => 'Laptops', 'slug' => 'laptops'],
                ['name' => 'Desktops', 'slug' => 'desktops'],
                ['name' => 'Monitors', 'slug' => 'monitors'],
                ['name' => 'Printers', 'slug' => 'printers'],
                ['name' => 'Scanners', 'slug' => 'scanners'],
                ['name' => 'Computer Accessories', 'slug' => 'computer-accessories'],
                ['name' => 'Storage Devices', 'slug' => 'storage-devices'],
                ['name' => 'Software', 'slug' => 'software'],
            ],
        ],
        [
            'name' => 'Gaming & Entertainment',
            'slug' => 'gaming-entertainment',
            'description' => 'Gaming PCs, laptops, monitors, peripherals and streaming gear for gamers and content creators.',
            'meta_title' => 'Gaming & Entertainment | Urban Focus',
            'meta_description' => 'Gaming laptops, PCs, monitors, peripherals and streaming equipment at Urban Focus with competitive pricing and fast delivery.',
            'children' => [
                ['name' => 'Gaming Laptops', 'slug' => 'gaming-laptops'],
                ['name' => 'Gaming PCs', 'slug' => 'gaming-pcs'],
                ['name' => 'Gaming Monitors', 'slug' => 'gaming-monitors'],
                ['name' => 'Gaming Keyboards', 'slug' => 'gaming-keyboards'],
                ['name' => 'Gaming Mice', 'slug' => 'gaming-mice'],
                ['name' => 'Gaming Headsets', 'slug' => 'gaming-headsets'],
                ['name' => 'Gaming Chairs', 'slug' => 'gaming-chairs'],
                ['name' => 'Streaming Equipment', 'slug' => 'streaming-equipment'],
                ['name' => 'Console Accessories', 'slug' => 'console-accessories'],
            ],
        ],
        [
            'name' => 'Smart Solutions',
            'slug' => 'smart-solutions',
            'description' => 'Smart home, office, transport, agriculture and IoT solutions for connected environments.',
            'meta_title' => 'Smart Solutions & IoT | Urban Focus',
            'meta_description' => 'Smart home, office, transport and IoT solutions from Urban Focus for schools, municipalities and modern businesses.',
            'children' => [
                ['name' => 'Smart Home', 'slug' => 'smart-home'],
                ['name' => 'Smart Office', 'slug' => 'smart-office'],
                ['name' => 'Smart School', 'slug' => 'smart-school'],
                ['name' => 'Smart Municipality', 'slug' => 'smart-municipality'],
                ['name' => 'Smart Transport', 'slug' => 'smart-transport'],
                ['name' => 'Smart Agriculture', 'slug' => 'smart-agriculture'],
                ['name' => 'IoT Devices', 'slug' => 'iot-devices'],
                ['name' => 'Smart Sensors', 'slug' => 'smart-sensors'],
                ['name' => 'Smart Lighting', 'slug' => 'smart-lighting'],
                ['name' => 'Smart Parking', 'slug' => 'smart-parking'],
            ],
        ],
        [
            'name' => 'Business & Retail Solutions',
            'slug' => 'business-retail',
            'description' => 'POS systems, barcode scanners, receipt printers and retail technology for shops and restaurants.',
            'meta_title' => 'Business & Retail Solutions | Urban Focus',
            'meta_description' => 'POS systems, barcode scanners, receipt printers and retail technology from Urban Focus with setup support across South Africa.',
            'children' => [
                ['name' => 'POS Systems', 'slug' => 'pos-systems'],
                ['name' => 'Barcode Scanners', 'slug' => 'barcode-scanners'],
                ['name' => 'Receipt Printers', 'slug' => 'receipt-printers'],
                ['name' => 'Label Printers', 'slug' => 'label-printers'],
                ['name' => 'Cash Drawers', 'slug' => 'cash-drawers'],
                ['name' => 'Attendance Systems', 'slug' => 'attendance-systems'],
                ['name' => 'Queue Management Systems', 'slug' => 'queue-management-systems'],
            ],
        ],
        [
            'name' => 'Industrial & Commercial Solutions',
            'slug' => 'industrial-commercial',
            'description' => 'Warehouse technology, asset tracking, environmental monitoring and industrial safety systems.',
            'meta_title' => 'Industrial & Commercial Solutions | Urban Focus',
            'meta_description' => 'Warehouse technology, asset tracking, environmental sensors and industrial safety systems from Urban Focus.',
            'children' => [
                ['name' => 'Warehouse Technology', 'slug' => 'warehouse-technology'],
                ['name' => 'Asset Tracking', 'slug' => 'asset-tracking'],
                ['name' => 'Environmental Sensors', 'slug' => 'environmental-sensors'],
                ['name' => 'Cold Chain Monitoring', 'slug' => 'cold-chain-monitoring'],
                ['name' => 'Industrial Cameras', 'slug' => 'industrial-cameras'],
                ['name' => 'Worker Safety Systems', 'slug' => 'worker-safety-systems'],
            ],
        ],
    ],

    /*
    | Old category slug → new canonical path (parent-slug/child-slug or parent-slug).
    */
    'legacy_slug_map' => [
        'laptops-notebooks' => 'computing-office/laptops',
        'business-laptops' => 'computing-office/laptops',
        'chromebooks' => 'computing-office/laptops',
        'laptop-bags' => 'computing-office/computer-accessories',
        'desktops' => 'computing-office/desktops',
        'business-desktops' => 'computing-office/desktops',
        'gaming-desktops' => 'gaming-entertainment/gaming-pcs',
        'all-in-one' => 'computing-office/desktops',
        'mini-pcs' => 'computing-office/desktops',
        'monitors-displays' => 'computing-office/monitors',
        'office-monitors' => 'computing-office/monitors',
        'gaming-monitors' => 'gaming-entertainment/gaming-monitors',
        'commercial-displays' => 'digital-signage/indoor-displays',
        'monitor-mounts' => 'computing-office/computer-accessories',
        'networking' => 'networking-connectivity',
        'network-switches' => 'networking-connectivity/switches',
        'routers-gateways' => 'networking-connectivity/routers',
        'fibre-sfp' => 'networking-connectivity/fibre-equipment',
        'cabinets-racks' => 'networking-connectivity/network-cabinets',
        'cctv-security' => 'security-surveillance',
        'vehicle-fleet' => 'security-surveillance/dash-cameras',
        'dash-cameras' => 'security-surveillance/dash-cameras',
        'ai-dash-cameras' => 'security-surveillance/ai-dash-cameras',
        'gps-trackers' => 'security-surveillance/gps-trackers',
        'reverse-cameras' => 'security-surveillance/reverse-cameras',
        'mdvr-systems' => 'security-surveillance/mdvr-systems',
        'body-worn-cameras' => 'security-surveillance/body-worn-cameras',
        'smart-helmet-cameras' => 'security-surveillance/smart-helmet-cameras',
        'passenger-counting-systems' => 'security-surveillance/passenger-counting-systems',
        'driver-monitoring-systems' => 'security-surveillance/driver-monitoring-systems',
        'fleet-monitoring-systems' => 'security-surveillance/fleet-monitoring-systems',
        'nvr-dvr' => 'security-surveillance/nvr-systems',
        'servers' => 'computing-office/storage-devices',
        'rack-servers' => 'computing-office/desktops',
        'tower-servers' => 'computing-office/desktops',
        'nas-storage' => 'computing-office/storage-devices',
        'server-components' => 'computing-office/computer-accessories',
        'laser-printers' => 'computing-office/printers',
        'inkjet-printers' => 'computing-office/printers',
        'ink-toner' => 'business-retail/receipt-printers',
        'software-licensing' => 'computing-office/software',
        'microsoft-365' => 'computing-office/software',
        'windows-licensing' => 'computing-office/software',
        'antivirus-security' => 'computing-office/software',
        'backup-software' => 'computing-office/software',
        'telephony-voip' => 'security-surveillance/intercom-systems',
        'ip-phones' => 'security-surveillance/intercom-systems',
        'pbx-gateways' => 'networking-connectivity/routers',
        'headsets' => 'gaming-entertainment/gaming-headsets',
        'peripherals' => 'computing-office/computer-accessories',
        'keyboards-mice' => 'computing-office/computer-accessories',
        'webcams-audio' => 'gaming-entertainment/streaming-equipment',
        'docking-stations' => 'computing-office/computer-accessories',
        'cables-adapters' => 'networking-connectivity/network-cables',
        'components-storage' => 'computing-office/storage-devices',
        'ssds-hdds' => 'computing-office/storage-devices',
        'memory-ram' => 'computing-office/computer-accessories',
        'graphics-cards' => 'gaming-entertainment/gaming-pcs',
        'cpus-motherboards' => 'computing-office/computer-accessories',
        'ups-power' => 'solar-power',
        'surge-protection' => 'solar-power/power-backup-solutions',
        'pdus-cables' => 'networking-connectivity/poe-equipment',
    ],

    'legacy_path_map' => [
        'cctv-security/ip-cameras' => 'security-surveillance/ip-cameras',
        'cctv-security/nvr-dvr' => 'security-surveillance/nvr-systems',
        'cctv-security/access-control' => 'security-surveillance/access-control',
        'cctv-security/alarm-systems' => 'security-surveillance/alarm-systems',
        'cctv-security' => 'security-surveillance',
        'vehicle-fleet' => 'security-surveillance',
        'vehicle-fleet/dash-cameras' => 'security-surveillance/dash-cameras',
        'vehicle-fleet/ai-dash-cameras' => 'security-surveillance/ai-dash-cameras',
        'vehicle-fleet/gps-trackers' => 'security-surveillance/gps-trackers',
        'vehicle-fleet/reverse-cameras' => 'security-surveillance/reverse-cameras',
        'vehicle-fleet/mdvr-systems' => 'security-surveillance/mdvr-systems',
        'vehicle-fleet/body-worn-cameras' => 'security-surveillance/body-worn-cameras',
        'vehicle-fleet/smart-helmet-cameras' => 'security-surveillance/smart-helmet-cameras',
        'vehicle-fleet/passenger-counting-systems' => 'security-surveillance/passenger-counting-systems',
        'vehicle-fleet/driver-monitoring-systems' => 'security-surveillance/driver-monitoring-systems',
        'vehicle-fleet/fleet-monitoring-systems' => 'security-surveillance/fleet-monitoring-systems',
        'networking/network-switches' => 'networking-connectivity/switches',
        'networking/routers-gateways' => 'networking-connectivity/routers',
        'networking/access-points' => 'networking-connectivity/access-points',
        'networking/fibre-sfp' => 'networking-connectivity/fibre-equipment',
        'networking/cabinets-racks' => 'networking-connectivity/network-cabinets',
        'networking' => 'networking-connectivity',
        'laptops-notebooks/business-laptops' => 'computing-office/laptops',
        'laptops-notebooks/gaming-laptops' => 'gaming-entertainment/gaming-laptops',
        'laptops-notebooks' => 'computing-office/laptops',
        'desktops/business-desktops' => 'computing-office/desktops',
        'desktops/gaming-desktops' => 'gaming-entertainment/gaming-pcs',
        'monitors-displays/office-monitors' => 'computing-office/monitors',
        'monitors-displays/gaming-monitors' => 'gaming-entertainment/gaming-monitors',
        'monitors-displays/commercial-displays' => 'digital-signage/indoor-displays',
        'printers/laser-printers' => 'computing-office/printers',
        'printers/ink-toner' => 'business-retail/receipt-printers',
        'software-licensing' => 'computing-office/software',
        'telephony-voip/ip-phones' => 'security-surveillance/intercom-systems',
        'telephony-voip/pbx-gateways' => 'networking-connectivity/routers',
        'ups-power/ups-systems' => 'solar-power/ups-systems',
        'ups-power' => 'solar-power',
        'peripherals' => 'computing-office/computer-accessories',
        'peripherals/cables-adapters' => 'networking-connectivity/network-cables',
        'components-storage' => 'computing-office/storage-devices',
        'servers/rack-servers' => 'computing-office/desktops',
        'servers/nas-storage' => 'computing-office/storage-devices',
    ],
];
