<?php

/**
 * Canonical storefront category tree and distributor → tree mappings.
 * Paths use parent-slug/child-slug (child optional).
 */
return [
    'tree' => [
        [
            'name' => 'Laptops & Notebooks',
            'slug' => 'laptops-notebooks',
            'children' => [
                ['name' => 'Business Laptops', 'slug' => 'business-laptops'],
                ['name' => 'Gaming Laptops', 'slug' => 'gaming-laptops'],
                ['name' => 'Chromebooks', 'slug' => 'chromebooks'],
                ['name' => 'Laptop Bags & Cases', 'slug' => 'laptop-bags'],
            ],
        ],
        [
            'name' => 'Desktops & Workstations',
            'slug' => 'desktops',
            'children' => [
                ['name' => 'Business Desktops', 'slug' => 'business-desktops'],
                ['name' => 'Gaming Desktops', 'slug' => 'gaming-desktops'],
                ['name' => 'All-in-One PCs', 'slug' => 'all-in-one'],
                ['name' => 'Mini PCs', 'slug' => 'mini-pcs'],
            ],
        ],
        [
            'name' => 'Monitors & Displays',
            'slug' => 'monitors-displays',
            'children' => [
                ['name' => 'Office Monitors', 'slug' => 'office-monitors'],
                ['name' => 'Gaming Monitors', 'slug' => 'gaming-monitors'],
                ['name' => 'Commercial Displays', 'slug' => 'commercial-displays'],
                ['name' => 'Monitor Arms & Mounts', 'slug' => 'monitor-mounts'],
            ],
        ],
        [
            'name' => 'Networking',
            'slug' => 'networking',
            'children' => [
                ['name' => 'Switches', 'slug' => 'network-switches'],
                ['name' => 'Routers & Gateways', 'slug' => 'routers-gateways'],
                ['name' => 'Wireless Access Points', 'slug' => 'access-points'],
                ['name' => 'Fibre & SFP Modules', 'slug' => 'fibre-sfp'],
                ['name' => 'Cabinets & Racks', 'slug' => 'cabinets-racks'],
            ],
        ],
        [
            'name' => 'CCTV & Security',
            'slug' => 'cctv-security',
            'children' => [
                ['name' => 'IP Cameras', 'slug' => 'ip-cameras'],
                ['name' => 'NVRs & DVRs', 'slug' => 'nvr-dvr'],
                ['name' => 'Access Control', 'slug' => 'access-control'],
                ['name' => 'Alarm Systems', 'slug' => 'alarm-systems'],
            ],
        ],
        [
            'name' => 'Servers & Storage',
            'slug' => 'servers',
            'children' => [
                ['name' => 'Rack Servers', 'slug' => 'rack-servers'],
                ['name' => 'Tower Servers', 'slug' => 'tower-servers'],
                ['name' => 'NAS Storage', 'slug' => 'nas-storage'],
                ['name' => 'Server Components', 'slug' => 'server-components'],
            ],
        ],
        [
            'name' => 'Printers & Scanners',
            'slug' => 'printers',
            'children' => [
                ['name' => 'Laser Printers', 'slug' => 'laser-printers'],
                ['name' => 'Inkjet Printers', 'slug' => 'inkjet-printers'],
                ['name' => 'Scanners', 'slug' => 'scanners'],
                ['name' => 'Ink & Toner', 'slug' => 'ink-toner'],
            ],
        ],
        [
            'name' => 'Software & Licensing',
            'slug' => 'software-licensing',
            'children' => [
                ['name' => 'Microsoft 365 & Office', 'slug' => 'microsoft-365'],
                ['name' => 'Windows Licensing', 'slug' => 'windows-licensing'],
                ['name' => 'Antivirus & Security', 'slug' => 'antivirus-security'],
                ['name' => 'Backup Software', 'slug' => 'backup-software'],
            ],
        ],
        [
            'name' => 'Telephony & VoIP',
            'slug' => 'telephony-voip',
            'children' => [
                ['name' => 'IP Phones', 'slug' => 'ip-phones'],
                ['name' => 'PBX & Gateways', 'slug' => 'pbx-gateways'],
                ['name' => 'Headsets', 'slug' => 'headsets'],
            ],
        ],
        [
            'name' => 'Peripherals & Accessories',
            'slug' => 'peripherals',
            'children' => [
                ['name' => 'Keyboards & Mice', 'slug' => 'keyboards-mice'],
                ['name' => 'Webcams & Audio', 'slug' => 'webcams-audio'],
                ['name' => 'Docking Stations', 'slug' => 'docking-stations'],
                ['name' => 'Cables & Adapters', 'slug' => 'cables-adapters'],
            ],
        ],
        [
            'name' => 'Components & Storage',
            'slug' => 'components-storage',
            'children' => [
                ['name' => 'SSDs & Hard Drives', 'slug' => 'ssds-hdds'],
                ['name' => 'Memory (RAM)', 'slug' => 'memory-ram'],
                ['name' => 'Graphics Cards', 'slug' => 'graphics-cards'],
                ['name' => 'CPUs & Motherboards', 'slug' => 'cpus-motherboards'],
            ],
        ],
        [
            'name' => 'UPS & Power',
            'slug' => 'ups-power',
            'children' => [
                ['name' => 'UPS Systems', 'slug' => 'ups-systems'],
                ['name' => 'Surge Protection', 'slug' => 'surge-protection'],
                ['name' => 'PDUs & Power Cables', 'slug' => 'pdus-cables'],
            ],
        ],
    ],

    /*
    | Esquire CategoryHead → canonical path (parent-slug/child-slug).
    */
    'esquire_heads' => [
        'Batteries' => 'ups-power/pdus-cables',
        'Bluetooth Products' => 'peripherals',
        'CCTV and DVR Accessories' => 'cctv-security',
        'CCTV and DVR Products' => 'cctv-security/nvr-dvr',
        'Cables & Adapters' => 'peripherals/cables-adapters',
        'Cameras & Camcorders' => 'cctv-security/ip-cameras',
        'Car Electronics' => 'peripherals',
        'Computer Chassis' => 'components-storage/cpus-motherboards',
        'Computer Cooling' => 'components-storage/cpus-motherboards',
        'Computer Gaming Accessories' => 'peripherals/keyboards-mice',
        'Computer Gaming Hardware' => 'desktops/gaming-desktops',
        'Computer Graphic Cards' => 'components-storage/graphics-cards',
        'Computer I/O Controllers' => 'components-storage/cpus-motherboards',
        'Computer Memory' => 'components-storage/memory-ram',
        'Computer Monitor Accessories' => 'monitors-displays/monitor-mounts',
        'Computer Monitors' => 'monitors-displays/office-monitors',
        'Computer Motherboards' => 'components-storage/cpus-motherboards',
        'Computer Optical Drives' => 'components-storage/ssds-hdds',
        'Computer Processors' => 'components-storage/cpus-motherboards',
        'Computer Software' => 'software-licensing',
        'Console Gaming Accessories' => 'peripherals/keyboards-mice',
        'Console Gaming Units' => 'peripherals',
        'Desktop  Computers' => 'desktops/business-desktops',
        'Flash Memory products' => 'components-storage/ssds-hdds',
        'Gadgets and Gifts' => 'peripherals',
        'HDMI Products' => 'peripherals/cables-adapters',
        'Hard Drive Enclosures' => 'components-storage/ssds-hdds',
        'Hard Drives/Storage' => 'components-storage/ssds-hdds',
        'IP Camera Products' => 'cctv-security/ip-cameras',
        'KVM Switches' => 'networking/network-switches',
        'Keyboards and Mice' => 'peripherals/keyboards-mice',
        'LED Lightning' => 'peripherals',
        'Licensed Products' => 'peripherals',
        'Line Drivers & Extenders' => 'networking/fibre-sfp',
        'Media Storage Solutions' => 'components-storage/ssds-hdds',
        'Mobile Phone Accessories' => 'peripherals',
        'Mobile Phone Covers' => 'peripherals',
        'Mobile and Smartphones' => 'peripherals',
        'Modems & Routers' => 'networking/routers-gateways',
        'Multimedia Accessories' => 'peripherals/webcams-audio',
        'Multimedia Players' => 'peripherals/webcams-audio',
        'Networking-Active' => 'networking/network-switches',
        'Networking-Passive' => 'networking/cabinets-racks',
        'Notebook Accessories' => 'laptops-notebooks',
        'Notebook Bags and Cases' => 'laptops-notebooks/laptop-bags',
        'Notebooks and Laptops' => 'laptops-notebooks/business-laptops',
        'Office Products' => 'peripherals',
        'Otg Products' => 'peripherals/cables-adapters',
        'Peripherals' => 'peripherals',
        'Point of Sale Products' => 'peripherals',
        'Power Supplies' => 'ups-power/pdus-cables',
        'Printer Accessories' => 'printers/ink-toner',
        'Printers' => 'printers/laser-printers',
        'Projectors and Accessories' => 'monitors-displays/commercial-displays',
        'Renewable Power Solutions' => 'ups-power',
        'Server Products' => 'servers/rack-servers',
        'Smart Boards' => 'monitors-displays/commercial-displays',
        'Smart Home' => 'cctv-security',
        'Speakers & Audio' => 'peripherals/webcams-audio',
        "Tablet PC's" => 'laptops-notebooks/business-laptops',
        "Tablet PC's Accessories" => 'laptops-notebooks',
        "Tablet PC's Covers" => 'laptops-notebooks/laptop-bags',
        'Telephone Equipment' => 'telephony-voip/ip-phones',
        'Televisions' => 'monitors-displays/commercial-displays',
        'Televisions- Accessories' => 'monitors-displays/monitor-mounts',
        'Toolkit and Test equipment' => 'peripherals',
        'USB Peripherals' => 'peripherals',
        'Uninterruptible Power Supply' => 'ups-power/ups-systems',
        'WebCams' => 'peripherals/webcams-audio',
        'Wireless Network Products' => 'networking/access-points',
    ],

    /*
    | Pinnacle category_tree prefix → canonical path.
    | Longer/more specific paths should appear first when matching.
    */
    'pinnacle_paths' => [
        'computing/notebooks' => 'laptops-notebooks/business-laptops',
        'computing/desktops' => 'desktops/business-desktops',
        'computing/monitors' => 'monitors-displays/office-monitors',
        'computing/memory' => 'components-storage/memory-ram',
        'computing/storage' => 'components-storage/ssds-hdds',
        'computing/components' => 'components-storage/cpus-motherboards',
        'computing/peripherals' => 'peripherals',
        'computing/printers' => 'printers/laser-printers',
        'computing/software' => 'software-licensing',
        'computing' => 'components-storage',
        'security/cctv' => 'cctv-security/ip-cameras',
        'security/access' => 'cctv-security/access-control',
        'security' => 'cctv-security',
        'networking/wireless' => 'networking/access-points',
        'networking/switches' => 'networking/network-switches',
        'networking/routers' => 'networking/routers-gateways',
        'networking' => 'networking',
        'point-of-sale' => 'peripherals',
        'enterprise/servers' => 'servers/rack-servers',
        'enterprise' => 'servers',
        'infrastructure/ups' => 'ups-power/ups-systems',
        'infrastructure' => 'ups-power',
    ],

    /*
    | Astrum distributor category → canonical path.
    */
    'astrum_categories' => [
        'Adapters & Converters' => 'peripherals/cables-adapters',
        'Cables' => 'peripherals/cables-adapters',
        'CAM' => 'cctv-security/ip-cameras',
        'Cleaning Solutions' => 'peripherals',
        'Cooling and Mousepad' => 'peripherals/keyboards-mice',
        'Earbuds' => 'peripherals/webcams-audio',
        'Enclosures' => 'components-storage/ssds-hdds',
        'FM Modulators' => 'peripherals',
        'Gadgets' => 'peripherals',
        'Gaming Products' => 'peripherals/keyboards-mice',
        'Headphones' => 'peripherals/webcams-audio',
        'Keyboards & Combo' => 'peripherals/keyboards-mice',
        'Laptop Bags' => 'laptops-notebooks/laptop-bags',
        'Laptop Batteries' => 'ups-power/pdus-cables',
        'Laptop Chargers' => 'ups-power/pdus-cables',
        'Laptop Keyboards' => 'peripherals/keyboards-mice',
        'Laptop Screens' => 'laptops-notebooks',
        'Memory Modules' => 'components-storage/memory-ram',
        'MOBILE CABLES' => 'peripherals/cables-adapters',
        'Mobile Chargers' => 'ups-power/pdus-cables',
        'Mobile Holders' => 'peripherals',
        'Mouse' => 'peripherals/keyboards-mice',
        'Networking' => 'networking',
        'Notebook PC' => 'laptops-notebooks/business-laptops',
        'Power Banks' => 'ups-power/pdus-cables',
        'SMART DEVICES' => 'peripherals',
        'Speakers' => 'peripherals/webcams-audio',
        'SSD DISK DRIVES' => 'components-storage/ssds-hdds',
        'Toner Cartridges' => 'printers/ink-toner',
        'USB Peripherals' => 'peripherals',
    ],

    /*
    | Scoop distributor brand → canonical path (fallback when name heuristics do not match).
    */
    'scoop_brands' => [
        'Ubiquiti' => 'networking/access-points',
        'MikroTik' => 'networking/routers-gateways',
        'TP-Link' => 'networking/access-points',
        'Cisco' => 'networking/network-switches',
        'Hikvision' => 'cctv-security/ip-cameras',
        'Dahua' => 'cctv-security/ip-cameras',
        'Yeastar' => 'telephony-voip/pbx-gateways',
        'Yealink' => 'telephony-voip/ip-phones',
        'Dell' => 'laptops-notebooks/business-laptops',
        'HP' => 'laptops-notebooks/business-laptops',
        'Lenovo' => 'laptops-notebooks/business-laptops',
        'Reyee' => 'networking/access-points',
        'Cudy' => 'networking/routers-gateways',
        'Fanvil' => 'telephony-voip/ip-phones',
        'Linkbasic' => 'peripherals/cables-adapters',
        'Rackstuds' => 'networking/cabinets-racks',
        'Locally Sourced' => 'networking',
        'Scoop' => 'networking',
    ],
];
