<?php

return [
    'range_label' => 'Specialist technology',

    'availability' => [
        'in_stock_za' => [
            'label' => 'IN STOCK – SOUTH AFRICA',
            'google' => 'in_stock',
            'schema' => 'https://schema.org/InStock',
            'days' => 3,
            'quote' => false,
        ],
        'eu_stock' => [
            'label' => 'EU STOCK – 5–10 BUSINESS DAYS',
            'google' => 'in_stock',
            'schema' => 'https://schema.org/InStock',
            'days' => 10,
            'quote' => false,
        ],
        'special_order_eu' => [
            'label' => 'SPECIAL ORDER – EUROPE',
            'google' => 'backorder',
            'schema' => 'https://schema.org/BackOrder',
            'days' => 21,
            'quote' => false,
        ],
        'request_quote' => [
            'label' => 'REQUEST A QUOTE',
            'google' => 'in_stock',
            'schema' => 'https://schema.org/LimitedAvailability',
            'days' => 14,
            'quote' => true,
        ],
        'contact_licensing' => [
            'label' => 'CONTACT US FOR LICENSING',
            'google' => 'in_stock',
            'schema' => 'https://schema.org/LimitedAvailability',
            'days' => 7,
            'quote' => true,
        ],
    ],

    'google_product_category' => [
        'fido-key' => '5032',
        'hsm' => '345',
        'encrypted-storage' => '1294',
        'mfa-bundle' => '5032',
        'pikvm' => '367',
        'cluster' => '325',
        'compute-module' => '325',
        'mini-server' => '325',
        'nas' => '1294',
        'industrial-pc' => '325',
        'plc' => '196',
        'iot-gateway' => '196',
        'ai-accelerator' => '203',
        'edge-ai' => '345',
        'network-tool' => '2335',
        'secure-router' => '199',
        'linux-pc' => '328',
        'smartphone' => '267',
        'software' => '313',
        'service' => '313',
        'firewall' => '199',
        'solution' => '313',
    ],

    'brands' => [
        ['name' => 'Nitrokey', 'website' => 'https://www.nitrokey.com'],
        ['name' => 'PiKVM', 'website' => 'https://pikvm.org'],
        ['name' => 'Turing Pi', 'website' => 'https://turingpi.com'],
        ['name' => 'ZimaBoard', 'website' => 'https://www.zimaboard.com'],
        ['name' => 'TECHBASE', 'website' => 'https://www.techbase.eu'],
        ['name' => 'Sfera Labs', 'website' => 'https://www.sferalabs.cc'],
        ['name' => 'Hailo', 'website' => 'https://hailo.ai'],
        ['name' => 'Netool.io', 'website' => 'https://netool.io'],
        ['name' => 'Turris', 'website' => 'https://www.turris.com'],
        ['name' => 'TUXEDO', 'website' => 'https://www.tuxedocomputers.com'],
        ['name' => 'Fairphone', 'website' => 'https://www.fairphone.com'],
        ['name' => 'Proxmox', 'website' => 'https://www.proxmox.com'],
        ['name' => 'Nextcloud', 'website' => 'https://nextcloud.com'],
        ['name' => 'Safetica', 'website' => 'https://www.safetica.com'],
        ['name' => 'Hornetsecurity', 'website' => 'https://www.hornetsecurity.com'],
        ['name' => 'MailStore', 'website' => 'https://www.mailstore.com'],
        ['name' => 'Checkmk', 'website' => 'https://checkmk.com'],
        ['name' => 'OpenProject', 'website' => 'https://www.openproject.org'],
        ['name' => 'ONLYOFFICE', 'website' => 'https://www.onlyoffice.com'],
        ['name' => 'OPNsense', 'website' => 'https://opnsense.org'],
        ['name' => 'Urban Focus', 'website' => 'https://www.urbanfocus.co.za'],
    ],
];
